# Generated by Django 4.2.7 on 2023-12-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
