# Generated by Django 4.2.7 on 2023-12-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulaire',
            new_name='Inscription',
        ),
    ]
